/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartHiringRouteImport } from './routes/start-hiring'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FindAJobRouteImport } from './routes/find-a-job'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as ServicesTalentOnDemandRouteImport } from './routes/services.talent-on-demand'
import { Route as ServicesEorRouteImport } from './routes/services.eor'
import { Route as ServicesDirectHireRouteImport } from './routes/services.direct-hire'
import { Route as RolesRoleIdRouteImport } from './routes/roles.$roleId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'

const StartHiringRoute = StartHiringRouteImport.update({
  id: '/start-hiring',
  path: '/start-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAJobRoute = FindAJobRouteImport.update({
  id: '/find-a-job',
  path: '/find-a-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoute,
} as any)
const ServicesTalentOnDemandRoute = ServicesTalentOnDemandRouteImport.update({
  id: '/services/talent-on-demand',
  path: '/services/talent-on-demand',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEorRoute = ServicesEorRouteImport.update({
  id: '/services/eor',
  path: '/services/eor',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDirectHireRoute = ServicesDirectHireRouteImport.update({
  id: '/services/direct-hire',
  path: '/services/direct-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoleIdRoute = RolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => RolesRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/find-a-job': typeof FindAJobRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/resources': typeof ResourcesRoute
  '/roles': typeof RolesRouteWithChildren
  '/start-hiring': typeof StartHiringRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/eor': typeof ServicesEorRoute
  '/services/talent-on-demand': typeof ServicesTalentOnDemandRoute
  '/roles/': typeof RolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/find-a-job': typeof FindAJobRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/resources': typeof ResourcesRoute
  '/start-hiring': typeof StartHiringRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/eor': typeof ServicesEorRoute
  '/services/talent-on-demand': typeof ServicesTalentOnDemandRoute
  '/roles': typeof RolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/find-a-job': typeof FindAJobRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/resources': typeof ResourcesRoute
  '/roles': typeof RolesRouteWithChildren
  '/start-hiring': typeof StartHiringRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/services/direct-hire': typeof ServicesDirectHireRoute
  '/services/eor': typeof ServicesEorRoute
  '/services/talent-on-demand': typeof ServicesTalentOnDemandRoute
  '/roles/': typeof RolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/find-a-job'
    | '/pricing'
    | '/referrals'
    | '/resources'
    | '/roles'
    | '/start-hiring'
    | '/legal/privacy'
    | '/legal/terms'
    | '/roles/$roleId'
    | '/services/direct-hire'
    | '/services/eor'
    | '/services/talent-on-demand'
    | '/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/find-a-job'
    | '/pricing'
    | '/referrals'
    | '/resources'
    | '/start-hiring'
    | '/legal/privacy'
    | '/legal/terms'
    | '/roles/$roleId'
    | '/services/direct-hire'
    | '/services/eor'
    | '/services/talent-on-demand'
    | '/roles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/find-a-job'
    | '/pricing'
    | '/referrals'
    | '/resources'
    | '/roles'
    | '/start-hiring'
    | '/legal/privacy'
    | '/legal/terms'
    | '/roles/$roleId'
    | '/services/direct-hire'
    | '/services/eor'
    | '/services/talent-on-demand'
    | '/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FindAJobRoute: typeof FindAJobRoute
  PricingRoute: typeof PricingRoute
  ReferralsRoute: typeof ReferralsRoute
  ResourcesRoute: typeof ResourcesRoute
  RolesRoute: typeof RolesRouteWithChildren
  StartHiringRoute: typeof StartHiringRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServicesDirectHireRoute: typeof ServicesDirectHireRoute
  ServicesEorRoute: typeof ServicesEorRoute
  ServicesTalentOnDemandRoute: typeof ServicesTalentOnDemandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-hiring': {
      id: '/start-hiring'
      path: '/start-hiring'
      fullPath: '/start-hiring'
      preLoaderRoute: typeof StartHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-job': {
      id: '/find-a-job'
      path: '/find-a-job'
      fullPath: '/find-a-job'
      preLoaderRoute: typeof FindAJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof RolesRoute
    }
    '/services/talent-on-demand': {
      id: '/services/talent-on-demand'
      path: '/services/talent-on-demand'
      fullPath: '/services/talent-on-demand'
      preLoaderRoute: typeof ServicesTalentOnDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/eor': {
      id: '/services/eor'
      path: '/services/eor'
      fullPath: '/services/eor'
      preLoaderRoute: typeof ServicesEorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/direct-hire': {
      id: '/services/direct-hire'
      path: '/services/direct-hire'
      fullPath: '/services/direct-hire'
      preLoaderRoute: typeof ServicesDirectHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId': {
      id: '/roles/$roleId'
      path: '/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof RolesRoleIdRouteImport
      parentRoute: typeof RolesRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RolesRouteChildren {
  RolesRoleIdRoute: typeof RolesRoleIdRoute
  RolesIndexRoute: typeof RolesIndexRoute
}

const RolesRouteChildren: RolesRouteChildren = {
  RolesRoleIdRoute: RolesRoleIdRoute,
  RolesIndexRoute: RolesIndexRoute,
}

const RolesRouteWithChildren = RolesRoute._addFileChildren(RolesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FindAJobRoute: FindAJobRoute,
  PricingRoute: PricingRoute,
  ReferralsRoute: ReferralsRoute,
  ResourcesRoute: ResourcesRoute,
  RolesRoute: RolesRouteWithChildren,
  StartHiringRoute: StartHiringRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServicesDirectHireRoute: ServicesDirectHireRoute,
  ServicesEorRoute: ServicesEorRoute,
  ServicesTalentOnDemandRoute: ServicesTalentOnDemandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
